# Generated by Django 3.2.7 on 2021-09-22 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_contact_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='organization',
        ),
    ]
